/** @type {Partial<import('tailwindcss').Config>} */
export default {
    theme: {
      extend: {
        colors: {
          core_palette: {
            "primary-1": "var(--colors-core_palette-primary-1, #003F2D)",
            "primary-2": "var(--colors-core_palette-primary-2, #17E88F)",
            "primary-3": "var(--colors-core_palette-primary-3, #012A2D)",
            "primary-4": "var(--colors-core_palette-primary-4, #435254)",
            "primary-5": "var(--colors-core_palette-primary-5, #CAD1D3)",
            "primary-6": "var(--colors-core_palette-primary-6, #DADFE0)",
          },
          brand: {
            "secondary-1": "var(--colors-brand-secondary-1, #032842)",
            "secondary-2": "var(--colors-brand-secondary-2, #538184)",
            "secondary-3": "var(--colors-brand-secondary-3, #80BBAD)",
            "secondary-4": "var(--colors-brand-secondary-4, #DBD99A)",
            "secondary-5": "var(--colors-brand-secondary-5, #7F8480)",
            "secondary-light-1": "var(--colors-brand-secondary-light-1, #778F9C)",
            "secondary-light-2": "var(--colors-brand-secondary-light-2, #96B3B6)",
            "secondary-light-3": "var(--colors-brand-secondary-light-3, #C0D4CB)",
            "secondary-light-4": "var(--colors-brand-secondary-light-4, #EFECD2)",
            "secondary-light-5": "var(--colors-brand-secondary-light-5, #CBDDC8)",
          },
          semantic: {
            text: "var(--colors-semantic-text, #435254)",
            black: "var(--colors-semantic-black, #4D4D4D)",
            white: "var(--colors-semantic-white, #FFFFFF)",
            error: "var(--colors-semantic-error, #E81717)",
            warning: "var(--colors-semantic-warning, #F1D230)",
            surface: "var(--colors-semantic-surface, #E6EAEA)",
            "system-1": "var(--colors-semantic-system-1, #000000)",
            "system-2": "var(--colors-semantic-system-2, #1A1A1A)",
            "system-3": "var(--colors-semantic-system-3, #333333)",
            "system-4": "var(--colors-semantic-system-4, #4D4D4D)",
            "system-5": "var(--colors-semantic-system-5, #666666)",
            "system-6": "var(--colors-semantic-system-6, #808080)",
            "system-7": "var(--colors-semantic-system-7, #999999)",
            "system-8": "var(--colors-semantic-system-8, #B3B3B3)",
            "system-9": "var(--colors-semantic-system-9, #CCCCCC)",
            "system-10": "var(--colors-semantic-system-10, #E6E6E6)",
            "system-11": "var(--colors-semantic-system-11, #FFFFFF)",
          },
        },
        fontFamily: {
          sans: ["var(--typography-fontFamily-sans, 'Inter', Arial, sans-serif)"],
          serif: ["var(--typography-fontFamily-serif, 'Noto Serif', Georgia, serif)"],
          mono: ["var(--typography-fontFamily-mono, 'Space Mono', monospace)"],
          "noto-serif": ["var(--typography-fontFamily-noto-serif, 'Noto Serif', 'georgia', serif)"],
          "noto-sans": ["var(--typography-fontFamily-noto-sans, 'Noto Sans', 'arial', sans-serif)"],
        },
        fontSize: {
          "10": "var(--typography-fontSize-10, 1rem)",
          "12": "var(--typography-fontSize-12, 1.2rem)",
          "14": "var(--typography-fontSize-14, 1.4rem)",
          "16": "var(--typography-fontSize-16, 1.6rem)",
          "18": "var(--typography-fontSize-18, 1.8rem)",
          "20": "var(--typography-fontSize-20, 2rem)",
          "22": "var(--typography-fontSize-22, 2.2rem)",
          "24": "var(--typography-fontSize-24, 2.4rem)",
          "32": "var(--typography-fontSize-32, 3.2rem)",
          "34": "var(--typography-fontSize-34, 3.4rem)",
          "36": "var(--typography-fontSize-36, 3.6rem)",
          "48": "var(--typography-fontSize-48, 4.8rem)",
          "60": "var(--typography-fontSize-60, 6rem)",
        },
        fontWeight: {
          light: "var(--typography-fontWeight-light, 300)",
          normal: "var(--typography-fontWeight-normal, 400)",
          medium: "var(--typography-fontWeight-medium, 500)",
          heavy: "var(--typography-fontWeight-heavy, 600)",
          bold: "var(--typography-fontWeight-bold, 700)",
        },
        lineHeight: {
          tight: "var(--typography-lineHeight-tight, 1.2)",
          snug: "var(--typography-lineHeight-snug, 1.3)",
          normal: "var(--typography-lineHeight-normal, 1.4)",
          relaxed: "var(--typography-lineHeight-relaxed, 1.5)",
          loose: "var(--typography-lineHeight-loose, 1.6)",
        },
        spacing: {
          "1": "var(--spacing-1, 8px)",
          "2": "var(--spacing-2, 16px)",
          "3": "var(--spacing-3, 24px)",
          "4": "var(--spacing-4, 32px)",
          "5": "var(--spacing-5, 40px)",
          "6": "var(--spacing-6, 48px)",
          "7": "var(--spacing-7, 56px)",
          "8": "var(--spacing-8, 64px)",
          "9": "var(--spacing-9, 72px)",
          "10": "var(--spacing-10, 80px)",
        },
        borderRadius: {
          none: "var(--shape-borderRadius-none, 0px)",
          sm: "var(--shape-borderRadius-sm, 2px)",
        },
        borderWidth: {
          default: "var(--shape-borderWidth-default, 1px)",
        },
        boxShadow: {
          none: "var(--shape-boxShadow-none, 0px 0px 0px 0px transparent)",
        },
      },
    },
  };
  